### PR TITLE
Represent single values without array prefix

### LINKED ISSUE #405: Crash when printing quasi-scalar arrays using format string
```python
import bohrium as np

a = np.array([1])
print("{:.2f}".format(np.sum(a)))
```

Works with NumPy, gives `ValueError` with Bohrium:

```
ValueError: Unknown format code 'f' for object of type 'str'
```

### PR DESCRIPTION
**Pull request by omegahm**
Fixes #405 by representing single values without the `array(...)` "prefix".

### CODE REVIEW

File: bridge/npbackend/src/_bh.c [hunk 1]
```diff
@@ -1105,7 +1105,44 @@ static PyObject* BhArray_Repr(PyObject *self) {
...
+                break;
+            case 'd': // double
+                snprintf(c, sizeof(c), "%.6g", *((npy_double*) data));
+                break;
+        }
+
+        if (c[0] == 0) {
+            str = PyArray_Type.tp_repr(t);
+        } else {
+            str = PyString_FromString(c);
```
Comment (madsbk) [inline bridge/npbackend/src/_bh.c]: Python3 doesn't have `PyString_FromString()` use something like:
```c
#if PY_MAJOR_VERSION > 2
    return PyUnicode_FromString(c);
#else
    return PyString_FromString(c);
#endif
```

Comment (omegahm) [reply bridge/npbackend/src/_bh.c]: I use the already defined `NPY_PY3K` in the above way.
